arcoiris=("Azul", "Verde", "Rojo")
print(arcoiris)
print("--Longitud arcoiris--")
print(len(arcoiris))
print("")
animales=("Pantera",20,"Estatura",1.7)
print(animales)
print("--Elementos de la tupla--")
print(animales[2])
print("")
rateros=("Juan", "ana", "Pedro")
y=list(rateros)
y[1]="Kiwi"
x=tuple(y)
print(x)
print("")
print("--Agregando elementos--")
Naminal=("Boby","Chetos")
y=list(Naminal)
y.append("Tontolin")
print(y)
print("")
print("Uso for en tuplas")
for elcolor in arcoiris:
    print(elcolor)
    print("")